services:
  db-agent:
    image: ghcr.io/calagopus/db-agent:latest
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "./config.yml:/etc/calagopus-db-agent/config.yml"
      # please note: if you change the /var/lib/calagopus-db-agent path and split it up, make sure to include the following paths properly (all in the config.yml):
      # /var/lib/calagopus-db-agent/data (used for storing database files)
      - "/var/lib/calagopus-db-agent/:/var/lib/calagopus-db-agent/"
      - "/var/log/calagopus-db-agent/:/var/log/calagopus-db-agent/"
      # do not mount directly to /etc/ssl/certs (right side), this will cause certificate issues within the container
      - "/etc/ssl/certs/db-agent:/etc/ssl/certs/db-agent:ro"
    command: ["/etc/calagopus-db-agent/config.yml"]
    ports:
      # PostgreSQL proxy (config: postgresql.bind)
      - 5432:5432
      # MariaDB/MySQL proxy (config: mariadb.bind)
      - 3306:3306
      # MongoDB proxy (config: mongodb.bind)
      - 27017:27017
      # Redis proxy (config: redis.bind)
      - 6379:6379
      # Management API (config: api.bind)
      - 8090:8090
